-- Ordered, typed steps that make up a lesson.
-- `content` is jsonb so new step types need no migration:
--   lecture  {"text": "..."}
--   question {"prompt": "...", "choices": [...], "answer": "..."}
--   video    {"url": "..."}
--   audio    {"url": "..."}

create table if not exists public.lesson_steps (
    id         bigint generated by default as identity primary key,
    lesson_id  bigint not null references public.lessons(id) on delete cascade,
    set_number integer not null default 1,
    sort       integer not null,
    type       text    not null check (type in ('lecture', 'question', 'video', 'audio')),
    content    jsonb   not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (lesson_id, set_number, sort)
);

create index if not exists lesson_steps_lesson_id_idx
    on public.lesson_steps (lesson_id, set_number, sort);

alter table public.lesson_steps enable row level security;

-- Course content is public to read; writes go through the secret key only.
create policy "lesson_steps are readable by everyone"
    on public.lesson_steps
    for select
    to anon, authenticated
    using (true);
