-- A lesson is made of ordered SETS. Each set is one thing: a lecture,
-- a multiple choice question, or later a video or audio clip.
-- lesson_steps was never populated, so it is replaced outright.

drop table if exists public.lesson_steps;

create table public.lesson_sets (
    id         bigint generated by default as identity primary key,
    lesson_id  bigint not null references public.lessons(id) on delete cascade,
    sort       integer not null,
    type       text    not null check (type in ('lecture', 'multiple_choice', 'video', 'audio')),
    content    jsonb   not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    unique (lesson_id, sort)
);

-- `content` shape depends on `type`:
--   lecture          {"text": "In Japanese, greetings change by time of day."}
--   multiple_choice  {"prompt": "How do you say Good Morning?",
--                     "choices": ["ohayou", "konnichiwa", "douzo"],
--                     "answer": "ohayou"}
--   video / audio    {"url": "https://..."}

create index lesson_sets_lesson_id_idx
    on public.lesson_sets (lesson_id, sort);

alter table public.lesson_sets enable row level security;

-- Course content is public to read; writes go through the secret key only.
create policy "lesson_sets are readable by everyone"
    on public.lesson_sets
    for select
    to anon, authenticated
    using (true);
