-- Lesson ids drifted to 23+ after repeated test inserts. Renumber to 1..n
-- and switch to GENERATED BY DEFAULT so explicit ids are allowed from now on.
-- Safe: lesson_sets is still empty, so no foreign keys point at lessons yet.

alter table public.lessons alter column id drop identity if exists;

with renumbered as (
    select id, row_number() over (order by id) as new_id
    from public.lessons
)
update public.lessons l
set id = r.new_id
from renumbered r
where l.id = r.id;

alter table public.lessons
    alter column id add generated by default as identity;

select setval(
    pg_get_serial_sequence('public.lessons', 'id'),
    coalesce((select max(id) from public.lessons), 1)
);
